### PR TITLE
feat(YouTube - Custom Filters): Custom filter whitelist

### PR DESCRIPTION
**Pull request by Francesco146**
I'll create this PR for discuss about this feature. Still feeling a bit unsteady about integrations patches.

Do you know a method to debug the integrations runtime patches directly in intellij? currently i don't know any other method to test my code, if not build the apk, install it, set up manually the filters and then test them. thanks!

linked to: https://github.com/anddea/revanced-patches/pull/409

### CODE REVIEW

**Comment by Francesco146** [comment]
@anddea sorry to bother you, can you tell me how do you work with the integrations? like, how do you debug line by line the java files in the integrations? i'm trying to fix this https://github.com/anddea/revanced-patches/issues/363, i hoped it was a simple fix in the resources xml, I need to do this in runtime so i need to modify how the integration work. 

I arrived at this portion of code:

https://github.com/anddea/revanced-integrations/blob/467a9542ac4b873901f947fd1b7d6a1f60a692f9/app/src/main/java/app/revanced/integrations/youtube/utils/ResourceHelper.kt#L33C1-L44C6


```kotlin
// file: java/app/revanced/integrations/youtube/utils/ResourceHelper.kt
    @JvmStatic
    fun hidePlayerButton(view: View, original: Int): Int {
        PlayerButton.COLLAPSE.apply {
            if (settings.boolean) {
                for (id in filter) {
                    if (view.id == identifier(id, ResourceType.ID))
                        return 8 // wft is 8??
                }
            }
        }
        return original // why return an int??
    }
```

but following the call chains i get nowhere, like if all these files aren't used in the root level. can you help me understand wth is going on? thanks xD

if you want, we can chat on Telegram or Discord to have a “faster” conversation

**Comment by anddea** [comment]
To debug, you can use LogHelper's print... (printDebug, printInfo, etc)
```java
LogHelper.printDebug(() -> "text message: " + variable);
```

Debug messages will be visible on your test machine in logcat. I think it will help you understand better than I can explain, but functions in integrations return something to fill smali code.

<details>
<summary>An exaggerated explanation</summary>

For example, you add smali instruction
```smali
opcode v{register_num}, "Lpath/to/function/MyFunction;"->"hideButton(view_or_whatever)"
```

and this hideButton can be smth like
```java
hideButton(){
    return 0;
}
```

and it will mean assign to specified register value 0 which means false.

For more information, get familiar with Smali and Dalvik bytecode. 

Dalvik opcodes: http://pallergabor.uw.hu/androidblog/dalvik_opcodes.html

</details>

To implement aforementioned issue, you can create new patch and name it "Force hide...", just duplicate patch like for "Hide player buttons background", one is made to work with Smali and it's buggy and the second ("Force...") is made to work with resources. You can take "Force hide player buttons background" as a reference, or patches to hide fullscreen button and chapters work the same way. You can just delete a node or zero it out. I don't think you need integrations for that. MondayNitro even mentioned what you can change (zero out width and height) and where (the filename). I think hide fullscreen button patch is very similar. 

I don't use Discord and opening Telegram once a week, you can send me your username.

**Comment by Francesco146** [comment]
@anddea hi! thank you a bunch for the more than exhaustive explanation. it's tremendously helpful to me since i'm new to this kind of project and i don't have many people i can ask, so once again thank you. 

thanks for the advice! actually i was thinking of working in the integrations module because i thought the Feature Request indicated wanting to make the toggle already present into a better version, which had the values in the resources adjusted at runtime level. now that i think back on it though, i don't think you can edit those xml files at runtime, just like you can't remove the fullscreen button through a toggle. with a compile-level patch, i think i can get away with it in no time! :))

alright, this is my telegram tag, as soon as you read it let me know i'll remove it from this comment:

[@FrancescoM_taken](https://t.me/FrancescoM_taken)

**Comment by anddea** [comment]
@Francesco146 I contacted you.

**Pull request closed without merging**
